# ==============================================================================
# Castle -- Docker desktops (container fast path)
# ==============================================================================
# Brings up a browser-served Linux desktop from clonewars/docker/<profile>/.
# Profiles:
#   arch-wine   Arch Linux + XFCE + Wine; launches every .exe in scripts/wine-apps
#   windows     Windows 11 in a KVM VM (dockur/windows); installs every .exe in
#               scripts/wine-apps at the end of setup and shares the folder as Z:
#
#   .\docker.ps1                    # up (builds on first run), prints the URL + login
#   .\docker.ps1 -Profile windows   # same for the Windows profile (first run: ~20 min install)
#   .\docker.ps1 -Build             # force a rebuild of the image
#   .\docker.ps1 -Logs              # follow container logs
#   .\docker.ps1 -Shell             # root shell inside the container
#   .\docker.ps1 -Down              # stop and remove the container (data is kept)
#   .\docker.ps1 -Down -Purge       # also delete the data (Wine prefix / the Windows disk)
#
# Needs a Docker engine: Docker Desktop (winget install Docker.DockerDesktop) or
# an engine inside WSL2. Everything is published on 127.0.0.1 only, with a login
# stored in docker/<profile>/.env (generated on first run).
#
# The windows profile needs KVM. Docker Desktop's WSL2 VM has the kvm_intel/kvm_amd
# modules but does not load them or create /dev/kvm by itself (and sometimes leaves
# a stray /dev/kvm directory), so this script fixes that inside the docker-desktop
# distro before every "up". It is not persistent: Docker Desktop restarts reset it.
# ==============================================================================
param (
    [ValidateSet("arch-wine", "windows")]
    [string]$Profile = "arch-wine",
    [switch]$Build,
    [switch]$Logs,
    [switch]$Shell,
    [switch]$Down,
    [switch]$Purge
)

$ErrorActionPreference = "Stop"
$ProfileDir = Join-Path (Join-Path $PSScriptRoot "docker") $Profile
$Compose = Join-Path $ProfileDir "compose.yml"
$EnvFile = Join-Path $ProfileDir ".env"

# Per-profile facts the generic flow below needs.
$Profiles = @{
    "arch-wine" = @{
        Url      = "https://127.0.0.1:3001   (self-signed certificate -- accept the browser warning)"
        Apps     = "every .exe in scripts\wine-apps launches under Wine when the desktop starts"
        UpNote   = "first run builds the image: Arch base + Wine, a few minutes"
        NeedsKvm = $false
        DataDir  = $null            # data lives in a named volume; 'down --volumes' removes it
    }
    "windows" = @{
        Url      = "http://127.0.0.1:8006    (web viewer; RDP: 127.0.0.1:3389 with the login below)"
        Apps     = "every .exe in scripts\wine-apps is installed at the end of Windows setup; the folder is drive Z:"
        UpNote   = "first run downloads Windows 11 and installs it unattended, ~20 min; watch it in the web viewer"
        NeedsKvm = $true
        DataDir  = $null            # the VM disk is a named volume (sparse on ext4; an NTFS bind mount allocates all 48 GB)
        # Local install media. Microsoft's download endpoints answer 403 from some
        # networks, so when this file exists it is bound in as /custom.iso via
        # compose.iso.yml and no download is attempted. Override with $env:CASTLE_WINDOWS_ISO.
        # Not Castle's win11-pro.iso: that one is split-WIM + Castle's answer file,
        # which dockur cannot drive. docker\windows\build-iso.ps1 makes this one
        # from data\win11-pro and is run automatically when the file is missing.
        Iso      = if ($env:CASTLE_WINDOWS_ISO) { $env:CASTLE_WINDOWS_ISO } else { Join-Path $PSScriptRoot "data\win11-pro-docker.iso" }
        IsoBuild = Join-Path $ProfileDir "build-iso.ps1"
    }
}
$P = $Profiles[$Profile]

if (-not (Test-Path $Compose)) {
    Write-Host "  [FAIL] No compose file for profile '$Profile' at $Compose" -ForegroundColor Red
    Exit 1
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "  [FAIL] docker not found on PATH." -ForegroundColor Red
    Write-Host "     Install Docker Desktop:  winget install Docker.DockerDesktop   (then reboot)" -ForegroundColor DarkGray
    Write-Host "     or an engine in WSL2:    wsl -d Ubuntu -- sudo apt install -y docker.io docker-compose-v2" -ForegroundColor DarkGray
    Exit 1
}

# -- Login: generate once, never commit --------------------------------------
if (-not (Test-Path $EnvFile)) {
    $Bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($Bytes)
    $Password = ([Convert]::ToBase64String($Bytes) -replace '[^A-Za-z0-9]', '').Substring(0, 24)
    $Tz = try { [System.TimeZoneInfo]::Local.Id } catch { "UTC" }
    @(
        "# Generated by docker.ps1 -- login for the '$Profile' desktop. Git-ignored; keep it private."
        "WEBTOP_USER=castle"
        "WEBTOP_PASSWORD=$Password"
        "TZ=$Tz"
    ) -join "`n" | Set-Content $EnvFile -NoNewline
    Write-Host "  [*] Generated web desktop login in $EnvFile" -ForegroundColor Yellow
}
$Login = @{}
Get-Content $EnvFile | ForEach-Object { if ($_ -match '^\s*([^#=\s]+)\s*=\s*(.*)$') { $Login[$Matches[1]] = $Matches[2].Trim() } }

$ComposeArgs = @("compose", "--project-directory", $ProfileDir, "-f", $Compose, "--env-file", $EnvFile)
if ($P.Iso) {
    $Starting = -not ($Down -or $Logs -or $Shell)
    if ($Starting -and -not (Test-Path $P.Iso) -and -not $env:CASTLE_WINDOWS_ISO -and $P.IsoBuild -and
        (Test-Path (Join-Path $PSScriptRoot "data\win11-pro\sources"))) {
        Write-Host "  [*] No $($P.Iso) yet; building it from data\win11-pro (5-15 min, one time)..." -ForegroundColor Yellow
        & $P.IsoBuild -Output $P.Iso
        if ($LASTEXITCODE -ne 0) { Exit $LASTEXITCODE }
    }
    if (Test-Path $P.Iso) {
        $env:WINDOWS_ISO = (Resolve-Path $P.Iso).Path
        $ComposeArgs += @("-f", (Join-Path $ProfileDir "compose.iso.yml"))
        if (-not $Down -and -not $Logs -and -not $Shell) {
            Write-Host "  [*] Installing from local ISO: $($env:WINDOWS_ISO)" -ForegroundColor Yellow
        }
    } elseif (-not $Down -and -not $Logs -and -not $Shell) {
        Write-Host "  [*] No local ISO at $($P.Iso); the container will try to download Windows from Microsoft" -ForegroundColor Yellow
        Write-Host "     (fails with 403 on some networks -- drop an ISO at that path or set CASTLE_WINDOWS_ISO)." -ForegroundColor DarkGray
    }
}

if ($Down) {
    $DownArgs = @("down")
    if ($Purge) { $DownArgs += "--volumes" }
    & docker @ComposeArgs @DownArgs
    $Rc = $LASTEXITCODE
    if ($Purge -and $P.DataDir -and (Test-Path $P.DataDir)) {
        Remove-Item -Recurse -Force $P.DataDir -Confirm:$false
    }
    Write-Host "  [OK] '$Profile' stopped$(if ($Purge) { ' and its data deleted' })." -ForegroundColor Green
    Exit $Rc
}
if ($Logs) { & docker @ComposeArgs logs -f; Exit $LASTEXITCODE }
if ($Shell) { & docker @ComposeArgs exec -it $Profile bash; Exit $LASTEXITCODE }

# -- KVM for the VM profiles (Docker Desktop on Windows 11) --------------------
if ($P.NeedsKvm) {
    $Distros = (& wsl -l -q 2>$null) -replace "`0", "" | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    if ($Distros -contains "docker-desktop") {
        $KvmFix = 'modprobe kvm_intel 2>/dev/null || modprobe kvm_amd 2>/dev/null; ' +
                  '[ -d /dev/kvm ] && rmdir /dev/kvm; sleep 1; ' +
                  '[ -c /dev/kvm ] || mknod /dev/kvm c 10 232; chmod 666 /dev/kvm; ' +
                  '[ -c /dev/kvm ] && echo kvm-ok'
        $KvmOut = & wsl -d docker-desktop -- sh -c $KvmFix 2>&1
        if ("$KvmOut" -match "kvm-ok") {
            Write-Host "  [OK] /dev/kvm ready in Docker Desktop's VM." -ForegroundColor Green
        } else {
            Write-Host "  [FAIL] Could not set up /dev/kvm in the docker-desktop distro: $KvmOut" -ForegroundColor Red
            Write-Host "     Needs Windows 11 with nested virtualization (default on) and the Docker Desktop WSL2 backend." -ForegroundColor DarkGray
            Exit 1
        }
    } else {
        Write-Host "  [*] No docker-desktop WSL distro; assuming the engine already exposes /dev/kvm." -ForegroundColor Yellow
    }
    if ($P.DataDir -and -not (Test-Path $P.DataDir)) { New-Item -ItemType Directory $P.DataDir | Out-Null }
}

$UpArgs = @("up", "-d")
if ($Build) { $UpArgs += "--build" }
Write-Host "  [DOCKER] Bringing up '$Profile' ($($P.UpNote))..." -ForegroundColor Cyan
& docker @ComposeArgs @UpArgs
if ($LASTEXITCODE -ne 0) {
    Write-Host "  [FAIL] docker compose up failed (exit $LASTEXITCODE)." -ForegroundColor Red
    Exit $LASTEXITCODE
}

Write-Host ""
Write-Host "  [OK] '$Profile' is up." -ForegroundColor Green
Write-Host "  * Desktop:  $($P.Url)" -ForegroundColor White
Write-Host "  * Login:    $($Login['WEBTOP_USER']) / $($Login['WEBTOP_PASSWORD'])" -ForegroundColor White
Write-Host "  * Apps:     $($P.Apps)" -ForegroundColor White
Write-Host "  * Stop:     .\docker.ps1 -Profile $Profile -Down" -ForegroundColor DarkGray
